# Generated by Django 5.0.2 on 2024-03-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentComplain',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain', models.CharField(max_length=500)),
                ('ans', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=500)),
                ('admintime', models.CharField(max_length=500)),
            ],
        ),
    ]
