# Generated by Django 5.0.2 on 2024-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentcomplain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=250)),
                ('adminpassword', models.CharField(max_length=250)),
                ('adminemail', models.EmailField(max_length=100)),
            ],
        ),
    ]
