# Generated by Django 5.0.4 on 2024-05-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
