# Generated by Django 5.0.4 on 2024-05-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_complain_studentcomplain_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='pay',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
